### PR TITLE
Isomorphic requests using fetch

### PR DESCRIPTION
**Pull request by dannynelson**
Support isomorphic requests thanks to [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch).

Breaking changes:
- no longer supports callbacks, since resource-client is just a wrapper around [fetch](https://developer.mozilla.org/en-US/docs/Web/API/GlobalFetch/fetch)
- return native Promise (or polyfill Promise) rather than Bluebird Promise
- Remove `Resource.action()`, so that we do not expose a configuration method on returned resource interface. Now you must create actions by passing in a configuration object. See README for details.
- Define actions with [fetch options](https://developer.mozilla.org/en-US/docs/Web/API/GlobalFetch/fetch) rather than [request options](https://github.com/request/request)
- No longer provide default actions. We should not make assumptions about how the user can interact with the API.

Thoughts @demands, @serhalp, @makebbekus, @golyshev?

### CODE REVIEW

**Comment by hazeledmands** [comment]
Awesome. I'm 100% in favor of this. Thanks @dannynelson!

**Comment by serhalp** [comment]
Super late here, but this is beautiful.  Let's merge it!

**Comment by makebbekus** [comment]
@dannynelson is this still relevant?

**Comment by dannynelson** [comment]
@makebbekus no, we prefer `json-fetch` / `goodeggs-fetch` now. Thanks for surfacing!

**Pull request closed without merging**
